version: '3.9'
services:
  tour-de-france-mvc:
    image: htflynn/tour-de-france-mvc:0.0.1.RELEASE
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - tour-de-france-db
    networks:
      - tour-network
    environment:
      DB_USER: postgres
      DB_HOST: tour-de-france-db 
      DB_NAME: tour-de-france
      DB_PASSWORD: mysecurepassword
      DB_PORT: 5432

  tour-de-france-db:
    image: htflynn/tour-de-france-db:0.0.1.RELEASE
    ports:
      - "5432:5432"
    restart: always
    networks:
      - tour-network
      
networks:
  tour-network: