- hosts: all
  become: true
  tasks:
    - name: Ensure docker-compose.yml exists
      stat:
        path: /home/ec2-user/docker-compose.yml
      register: compose_file

    - name: Fail if docker-compose.yml is missing
      fail:
        msg: "docker-compose.yml not found in /home/ec2-user/"
      when: not compose_file.stat.exists

    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/ec2-user/
